const commonTags = [
  "name",
  "fatherName",
  "motherName",
  "jobTitle",
  "employeeId",
  "affiliation",
  "institution",
  "companyName",
  "researchAreas",
  "dateOfBirth",
  "identityNo",
  "address",
  "email",
  "education",
  "phone",
  "workExperience",
  "publications",
  "skills",
  "eTin",
  "National Identity No",
  "Passport No",
  "Nationality",
  "University ID",
  "University Address",
  "University Phone",
  "University Department",
  "Form No",
  "Voter Area",
  "Voter Serial",
  "Voter No",
  "Status",
  "Blood Group",
  "Address",
  "Present Address",
  "Permanent Address",
  "registrationDate",
  "issueDate",
  "registerNo",
  "Gender",
  "birthPlace",
];

module.exports = {
  commonTags,
};
